apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: test-nginx
  labels:
    app: test-nginx
spec:
  clusterIP: None
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: test-nginx
